# Site settings
title: "SLING AI"
description: "Symbolic Logic Inspires Non-erroneous Generative AI"
logo: "/assets/images/company_logo.png"

url: https://ylee-sling.github.io/sling-ai-webpage

# Theme settings
remote_theme: just-the-docs




# Footer Content
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y"
footer_content: "Copyright © 2026 슬링에이아이 주식회사(SLING AI Inc.). All rights reserved."

