# Site settings
title: "SLING AI"
description: "Symbolic Logic Inspires Non-erroneous Generative AI"

# 중요: 주소 설정 (양쪽 따옴표를 꼭 넣어주세요)
url: "https://ylee-sling.github.io"
baseurl: "/sling-ai-webpage"

# 중요: 테마 설정 (remote_theme만 남기고 일반 theme: 는 삭제하세요)
remote_theme: just-the-docs/just-the-docs

# Jekyll 설정
plugins:
  - jekyll-remote-theme

# Just the Docs 설정
aux_links:
  "Just the Docs on GitHub":
    - https://github.com/just-the-docs/just-the-docs
    
    
exclude:
  - README.md